apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tts
  name: tts
  namespace: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tts
  template:
    metadata:
      labels:
        app: tts
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: registry.hub.docker.com/${REPO_NAME}/tts:latest
          name: tts
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 300m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tts-svc
  namespace: spring-boot
spec:
  type: NodePort
  selector:
    app: tts
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30234